name: Build binary files for release

on:
  release:
    types:
      - 'created'
      - 'edited'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            architecture: x64
          - os: ubuntu-latest
            architecture: x64
          - os: ubuntu-latest
            architecture: arm64
          - os: macos-latest
            architecture: x64
          - os: macos-latest
            architecture: arm64

    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} with ${{ matrix.architecture }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install -r requirements.txt
    - run: pip install pyinstaller
    - run: pyinstaller main.spec
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
