name: Build and run tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  merge_group:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pip install -r requirements.txt
    - run: python main.py --version
    - run: pip install pyinstaller
    - run: pyinstaller main.spec
    - run: mv `ls -d dist/petalvault*` dist/petalvault
    - run: dist/petalvault --version
